name: puzzle
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.1+201
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: 3.2.2
  pull_to_refresh: 2.0.0

  # Network
  dio: 5.0.2
  pretty_dio_logger: 1.3.1
  retrofit: ^4.1.0
  # DI
  injectable: 2.1.0
  get_it: 7.2.0

  # Model gen
  freezed: 2.3.0


  equatable: 2.0.5
  dartz: 0.10.1

  # env
  freezed_annotation: ^2.4.1
  get: 4.6.5
  flutter_easyloading: ^3.0.5
  lottie: 1.4.3
  # firebase_core: 2.9.0
  # cloud_firestore: 4.5.0
  # firebase_database: 10.1.0
  image_picker: 0.8.7+2
  path: ^1.8.2
  # firebase_storage: ^11.1.0
  cupertino_icons: ^1.0.2
  circular_countdown_timer: 0.2.2
  shared_preferences: ^2.2.0
  in_app_purchase: ^3.1.8

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  injectable_generator: 2.1.4
  build_runner: 2.3.3
  json_serializable: 6.6.0
  retrofit_generator: 6.0.0+1
  copy_with_extension_gen: 5.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/images/
    - assets/lotties/

flutter_gen:
  output: lib/core/assets_gen/
  assets:
    enable: true
  font:
    enable: true