// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHNNyLEdY9yCJS3anz0tEEJVIBNkWP4yk',
    appId: '1:587997386916:ios:7e79dbbb2aeb42b5c8ee31',
    messagingSenderId: '587997386916',
    projectId: 'game1-puzzle',
    databaseURL: 'https://game1-puzzle-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'game1-puzzle.appspot.com',
    iosBundleId: 'com.example.puzzle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHNNyLEdY9yCJS3anz0tEEJVIBNkWP4yk',
    appId: '1:587997386916:ios:7e79dbbb2aeb42b5c8ee31',
    messagingSenderId: '587997386916',
    projectId: 'game1-puzzle',
    databaseURL: 'https://game1-puzzle-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'game1-puzzle.appspot.com',
    iosBundleId: 'com.example.puzzle',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2MUkUye9pVbw8N-59Ww96fHPHyHqQ5WY',
    appId: '1:587997386916:web:1b9459bc59425d00c8ee31',
    messagingSenderId: '587997386916',
    projectId: 'game1-puzzle',
    authDomain: 'game1-puzzle.firebaseapp.com',
    databaseURL: 'https://game1-puzzle-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'game1-puzzle.appspot.com',
    measurementId: 'G-V7RBFTYESQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxvR9jUhx3OF6T0UlMXWIfaqCnn41VRok',
    appId: '1:587997386916:android:d4727853d9f96b58c8ee31',
    messagingSenderId: '587997386916',
    projectId: 'game1-puzzle',
    databaseURL: 'https://game1-puzzle-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'game1-puzzle.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2MUkUye9pVbw8N-59Ww96fHPHyHqQ5WY',
    appId: '1:587997386916:web:eedbd6b968db6d31c8ee31',
    messagingSenderId: '587997386916',
    projectId: 'game1-puzzle',
    authDomain: 'game1-puzzle.firebaseapp.com',
    databaseURL: 'https://game1-puzzle-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'game1-puzzle.appspot.com',
    measurementId: 'G-27TJK7YK6K',
  );

}